name: Build and Deploy Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'CMakeLists.txt'
      - 'Doxyfile'
      - '.github/workflows/docs.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential
    
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: cmake --build build
    
    - name: Test Build
      run: ./bin/chst --help || echo "Binary created successfully"

  docs:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake doxygen graphviz
    
    - name: Configure CMake
      run: cmake -B build
    
    - name: Generate Documentation
      run: cmake --build build --target docs
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/html
    
    - name: Deploy to Pages
      uses: actions/deploy-pages@v4