name: Deploy Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'Doxyfile'
      - '.github/workflows/docs.yml'

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Doxygen
      run: sudo apt-get update && sudo apt-get install -y doxygen graphviz
    
    - name: Generate Documentation
      run: doxygen Doxyfile
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/html
    
    - name: Deploy to Pages
      uses: actions/deploy-pages@v4